### PR TITLE
Add comment for DiscordGameStatus's %online%

### PR DESCRIPTION
**Pull request by J-295**
If no changes are wanted for the EN config then I will translate it for the other languages.

### CODE REVIEW

**Review by Dinty1 — COMMENTED** [review]
Why the indentation?

**Comment by J-295** [comment]
> Why the indentation?

This was based on existing comments:
```
# DiscordConsoleChannelUsageLog:
#    %date%:  current date
#              example: 2017-01-01
#    PlaceholderAPI placeholders are supported
```

**Review by Dinty1 — APPROVED** [review]
OK

**Review by ANutley — CHANGES_REQUESTED** [review]
When the phrase "PlaceholderAPI placeholders are supported" has already been translated previously leave the translated phrase if not just leave it as English

**Review by ANutley — APPROVED** [review]
Thank you! :)

**Pull request merged**
