### PR TITLE
chinese translation

### PR DESCRIPTION
**Pull request by kizajan**
add the translation of traditional Chinese

### CODE REVIEW

**Comment by Scarsz** [comment]
How do you get around the GFW's block of Discord? I don't know how useful this would be to merge since nobody's able to use Discord in China without VPNs/proxies anyway.

**Comment by kizajan** [comment]
dude...lots of people speak chinese , not only in china

**Comment by Scarsz** [comment]
Clearly people speak Chinese outside of China... 😐

My point is that how many people are actually going to be using this translation when Discord itself is banned in China? The primary population that speaks Chinese can't use the service that this plugin is made to use.

**Comment by kizajan** [comment]
idn
maybe more than the estonian speakers

**Comment by Vankka** [comment]
There are a few countries south of China that do have a lot of Chinese speakers, indeed with higher population than Estonia

**Pull request merged**
