### PR TITLE
Update Chatty api to 3.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by sub-kek**
Fix DiscordSRV does not work with Chatty version 3.0.0-SNAPSHOT. This will break hook Chatty 2.19.14 or below.

### CODE REVIEW

**Review by granny — CHANGES_REQUESTED** [review]
Blocking this PR until builds of [Chatty](https://github.com/Brikster/Chatty) v3.0.0 become public

**Comment by sub-kek** [comment]
This PR is for the future.

**Comment by granny** [comment]
> This PR is for the future.

Right. I made sure to make a note of that so it doesn't get merged haphazardly.

**Review by Scarsz — CHANGES_REQUESTED** [review]
Not a fan of breaking the compatibility with Chatty 2.x, there can be two versions of the hook that can be dynamically chosen

**Comment by Boddebon** [comment]
Hello, is it possible to make it so that users can enable this at their own risk, because some servers have already switched to Chatty V3, but they disable chats in Discord because of this problem?

**Comment by Dinty1** [comment]
If Scarsz’ comment is addressed it could probably be merged

**Comment by PadowYT2** [comment]
> Hello, is it possible to make it so that users can enable this at their own risk, because some servers have already switched to Chatty V3, but they disable chats in Discord because of this problem?

I could help you build it yourself, or straight up send you the .jar if you want. DM me on Discord (IGN - `padowyt2`)

**Comment by granny** [comment]
> > Hello, is it possible to make it so that users can enable this at their own risk, because some servers have already switched to Chatty V3, but they disable chats in Discord because of this problem?
> 
> I could help you build it yourself, or straight up send you the .jar if you want. DM me on Discord (IGN - `padowyt2`)

I do not recommend anybody do this at all. This is dangerous and you have no guarantee that the person sending you the file didn't make any additional modifications to it.

**Comment by sub-kek** [comment]
Maybe I'll make a second hook for Chatty V3 just without the dependencies.

**Comment by granny** [comment]
> Maybe I'll make a second hook for Chatty V3 just without the dependencies.

@sub-kek Why not depend on both v2 and v3 api's and use the one that's available at runtime? That's what scarsz suggested.

**Comment by sub-kek** [comment]
> > Maybe I'll make a second hook for Chatty V3 just without the dependencies.
> 
> 
> 
> @sub-kek Why not depend on both v2 and v3 api's and use the one that's available at runtime? That's what scarsz suggested.

The v3 api is not published anywhere yet this may cause problems with the build.

**Comment by granny** [comment]
> > > Maybe I'll make a second hook for Chatty V3 just without the dependencies.
> > 
> > 
> > @sub-kek Why not depend on both v2 and v3 api's and use the one that's available at runtime? That's what scarsz suggested.
> 
> The v3 api is not published anywhere yet this may cause problems with the build.

We can publish it on scarsz' nexus repo so that's not a problem.

**Comment by Boddebon** [comment]
Hello, do you have any information?

**Comment by sub-kek** [comment]
> We can publish it on scarsz' nexus repo so that's not a problem.

I think it should be done.  Some people ask how to build it.

**Pull request closed without merging**
