### PR TITLE
Add secondary api for GeyserMC

### PR DESCRIPTION
**Pull request by Creeperz653**
This API supports both bedrock account and java accounts docs incase you guys need it: https://api-docs.creepernation.net/

### CODE REVIEW

**Review by Scarsz — CHANGES_REQUESTED** [review]
Change needs to be done to all language files

**Comment by Creeperz653** [comment]
> Change needs to be done to all language files

Alright I’ll do that when I’m home

**Comment by Creeperz653** [comment]
Finished

**Comment by Creeperz653** [comment]
What do you think

**Comment by Vankka** [comment]
Don't bump pull requests

**Comment by Creeperz653** [comment]
> Don't bump pull requests

i was serious by what they though incase i need any changes

**Comment by Creeperz653** [comment]
Domain Update sorry this wont happen again.

**Comment by granny** [comment]
not happening

**Comment by Creeperz653** [comment]
Can I get a reason?

**Comment by ANutley** [comment]
Hey, we appreciate the effort but we're planning to implement our own heads service, which will also account for Geyser avatars, at some point in the future. Thanks again :)

**Comment by Creeperz653** [comment]
> Hey, we appreciate the effort but we're planning to implement our own heads service, which will also account for Geyser avatars, at some point in the future. Thanks again :)

i love how you tell me but the other person gives me little to no info lmao thanks for telling me tho

**Comment by thewilloftheshadow** [comment]
We all coordinate these together, but sorry that it wasn't made clear when the PR was first closed! 😅

**Comment by Creeperz653** [comment]
2

> We all coordinate these together, but sorry that it wasn't made clear when the PR was first closed! 😅

yea try to have good uptime even geysers up time is all over the place

**Pull request closed without merging**
