### PR TITLE
Overhauled internal account linking implementations

### PR DESCRIPTION
**Pull request by Scarsz**

### CODE REVIEW

**Review by Vankka — CHANGES_REQUESTED** [review]
Here's some general comments;
- We may want to store if a player has already been linked once, so if they unlink & link again we can have a option to not give out (specific) rewards
- I'm guessing there's probably a plan to for doing as little mysql/http on the main thread, but if there isn't there probably should be (https://github.com/DiscordSRV/DiscordSRV/issues/776)

also left a few inline comments

**Comment by Scarsz** [comment]
> * I'm guessing there's probably a plan to for doing as little mysql/http on the main thread, but if there isn't there probably should be (#776)

Went ahead and added some async methods to the providers https://github.com/DiscordSRV/DiscordSRV/pull/865/commits/21a8661bc99d9ba68d6ab5d26b266a4428696c59

**Comment by Vankka** [comment]
> Went ahead and added some async methods to the providers 21a8661

In the instance of https://github.com/DiscordSRV/DiscordSRV/issues/776, LuckPerms' ContextCalculator this wouldn't work, see javadoc comment: https://github.com/lucko/LuckPerms/blob/2ea43d4b2ee63aa13eac63c6d6dd1d0fc7c1fd15/api/src/main/java/net/luckperms/api/context/ContextCalculator.java#L39-L43

**Comment by Scarsz** [comment]
> In the instance of #776, LuckPerms' ContextCalculator this wouldn't work, see javadoc comment: https://github.com/lucko/LuckPerms/blob/2ea43d4b2ee63aa13eac63c6d6dd1d0fc7c1fd15/api/src/main/java/net/luckperms/api/context/ContextCalculator.java#L39-L43

I feel that's an issue best handled inside the `ContextCalculator` itself, the providers being async should be enough to cover the feature set of a provider

Maybe there could be a `CachedAccountSystem` subclass to implement that functionality as well

**Pull request closed without merging**
