### PR TITLE
Add channel specific formatting

### PR DESCRIPTION
**Pull request by garagepoort**
I created this PR to allow users to specify a discord to minecraft formatting per channel.
If you have no channel specific formatting defined it will fall back on the default format.

This allows you to do something like this:

In config.yml
```
Channels: {"global": "xxxxxxxxxxxx", "staffplusplus-staffchat": "xxxxxxxxxxxxxxxxxxx"}
```

In messages.yml
```
DiscordToMinecraftChatMessageFormat: "[&bDiscordsss &r| %toprolecolor%%toprole%&r] %name% » %message%"
DiscordToMinecraftChatMessageFormatNoRole: "[&bDiscord&r] %name% » %message%"

DiscordToMinecraftChatMessageFormat_staffplusplus-staffchat: "[&bDiscord_MySpecialChannel&r| %toprolecolor%%toprole%&r] %name% » %message%"
DiscordToMinecraftChatMessageFormatNoRole_staffplusplus-staffchat: "[&bDiscord_MySpecialChannel&r] %name% » %message%"
```

This way formatting can be set using basic configuration and it doesn't require any special development work for other plugins.

### CODE REVIEW

**Review by Vankka — COMMENTED** [review]
This should be documented in the messages.yml (in the comment for the base options), for the other languages (excluding English & Estonian) you can use our bot on our Discord server (https://discord.discordsrv.com). I can give you access & instruct me, just @ me (Vankka#1337) & say it's regarding the translation bot

**Comment by garagepoort** [comment]
@Vankka I updated the messages files. Out of curiosity, why don't we need to update the English and Estonian files?

**Comment by Vankka** [comment]
Ah, I meant that they don't need to be translated, they just need the English comments. The Estonian translated opted to keep the config files in English so we're keeping it that way

**Comment by garagepoort** [comment]
> Ah, I meant that they don't need to be translated, they just need the English comments. The Estonian translated opted to keep the config files in English so we're keeping it that way

Ok updated 👍

**Review by Vankka — APPROVED** [review]

**Comment by garagepoort** [comment]
Hey @Vankka 

Do you have any idea when this will be merged.
Are we still waiting on something to be completed?

**Pull request merged**
